// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0XMiyDIjPu0lKzIfwSbqPE1DfgL6jVvg',
    appId: '1:768941091747:android:878bedadd7d2c0d35e8816',
    messagingSenderId: '768941091747',
    projectId: 'fir-project-2fc88',
    storageBucket: 'fir-project-2fc88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj6b0AcCzja0kn_wBykuIELJ7IPKf-ww',
    appId: '1:768941091747:ios:139077ad468314a35e8816',
    messagingSenderId: '768941091747',
    projectId: 'fir-project-2fc88',
    storageBucket: 'fir-project-2fc88.firebasestorage.app',
    androidClientId: '768941091747-fcjre75gbic9essibccbvjivpmju0kcq.apps.googleusercontent.com',
    iosClientId: '768941091747-v7hbb5bq9gdr3gtn5nro6kfjp7v4174s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseHomework',
  );
}
